### PR TITLE
Configure flycheck-rust and racer packages

### PR DESCRIPTION
**Pull request by dcorking**
Would you like this in your `init-rust` ?

### CODE REVIEW

**Comment by dcorking** [comment]
pls don't merge this yet - I am getting some infinite loops on rust compilation that _might_ be caused by my project, but just _might_ be a result of the Emacs Lisp code on this branch

**Comment by purcell** [comment]
Yep, would be interested in this, though I'm not actively working with Rust, so no big deal. :-)

**Comment by dcorking** [comment]
No infinite loop now (seemed to be projectile-related, not rust at all, but fixed by updating some packages.)

flycheck and racer both work nicely for me (although flycheck's idle-change and new-line features don't seem to work - perhaps rustc needs the file to be saved)

So this is ready to be merged when you are, IMO.

**Comment by dcorking** [comment]
From[ gitter.im/flycheck/flycheck](https://gitter.im/flycheck/flycheck?at=5aaa51fb8f1c77ef3ac2cc67)
> David Corking @dcorking 10:59
I am using flycheck-rust and noticed that I don't get checks after the buffer has been idle, or when I add a new line, even though I have idle-change and new-line on. (They work in other languages such as ruby and js.) Is this expected in rust?
> fmdkdd @fmdkdd 09:54
@dcorking cargo does not support checking files that are not saved, so yes this is expected.
> David Corking @dcorking 12:59
I suspected that might be the reason. Thanks.
> fmdkdd @fmdkdd 13:01
You might want to take a look at https://github.com/emacs-lsp/lsp-rust/ if you want faster feedback

**Comment by purcell** [comment]
Great, thanks. I made a further little tweak to ensure `flycheck-rust` doesn't get loaded until the user starts working with rust-mode.

**Pull request merged**
