### PR TITLE
Remove all form feed (^L) characters

### PR DESCRIPTION
**Pull request by jrasanen**
The diff in this pull request looks very silly, I know. I removed all the invisible [form feed characters](https://www.asciihex.com/character/control/12/0x0C/ff-form-feed).

Took a while to figure out that these characters were the root cause of the odd issues I had getting this to work on Windows properly. They caused no issues on macOS or Linux. :)

## Some visualization of the characters

CleanShot 2023-03-11 at 20 04 55@2x
CleanShot 2023-03-11 at 20 05 24@2x

### CODE REVIEW

**Comment by purcell** [comment]
But this is why I wrote (and have enabled, in this exact configuration) the `page-break-lines` package. These characters appear as neat horizontal lines for me, and they are deliberately present.

**Comment by purcell** [comment]
From the screenshot it looks like you're using a different or heavily modified config, in which you can of course unilaterally remove these characters.

**Comment by jrasanen** [comment]
> But this is why I wrote (and have enabled, in this exact configuration) the page-break-lines package. These characters appear as neat horizontal lines for me, and they are deliberately present.

Right, thanks for the reply! That's good to know - I'll close the MR as these were intended then.

> From the screenshot it looks like you're using a different or heavily modified config, in which you can of course unilaterally remove these characters.

Yes, in the screenshots, I visualized the characters using a command line tool `bat` and Sublime Text. My emacs didn't like these for some reason.

**Comment by purcell** [comment]
Ah! Here's how they look for me:

Screenshot 2023-03-13 at 15 50 53

**Pull request closed without merging**
